Syntax v1
arkedge/opslang pull request #7
Opened 2024-02-07 09:40 UTC by kobkaz

2024-02-07 11:53 UTC, s-ylide requested changes
動かしてませんが、読んで気になったところコメント入れました ご意見を伺いたく

2024-02-07 11:53 UTC, s-ylide commented on tests/test.ops
> +print hk.OBC.XX.YY                  # テレメトリ集合型は構造体のように参照できる
テレメトリの参照(？)が以降でどう処理されるかわかりませんが、記号$を使っているのってどういう理由ですか？ここを見るに、値を評価するという意味よりは識別のためだけに使われているように読めました 後者なら、テレメトリの識別子をidentとかpathとして読んでおいて先頭がcapitalかで分岐、などにより読み分けが可能だと思っていて、積極的に$を無くしたいです

2024-02-07 11:53 UTC, s-ylide commented on opslang-parser/src/lib.rs
> +            = e:expr() ":" { e } // TODO: これで大丈夫か検討
糖衣構文の`10:`のラベルっぽい記法を踏襲しているんですよね、これ
左側に文字があると浮いちゃうので、`@`より前にのみ出現を許すとか、`@10`にしてスタイルを揃えるとかいかがでしょうか

2024-02-07 11:53 UTC, s-ylide commented on opslang-parser/src/lib.rs
> +            / "time!" _ "(" _ content:$([c if c != ')']*) _ ")" {?
文字列として扱っているわけではないので、もう直接(`time!`とparen無しで)リテラルとして書ける方が良いと思いました PRは分けても分けなくても

2024-02-07 11:53 UTC, s-ylide commented on opslang-parser/src/lib.rs
> +            = "assert_approx_eq" __ left:expr() _ "," _ right:expr() _ "," _ tolerance:expr()
parenがなくてcommaがあるの中途半端感あります 他と揃えるなら無くて良いのでは？(expr expr)による適用の文法は想定せずこれまでも作っていました

2024-02-07 11:53 UTC, s-ylide commented on opslang-parser/src/lib.rs
> +            = _ default_receiver_component:("@" r:receiver(){r})? _ delay:block_delay()?
ここ、spannedの内部に来る部分にwsの読み飛ばしを先頭に入れるとspanがずれると思います

2024-02-07 11:54 UTC, s-ylide commented on tests/test.ops
> +print hk.OBC.XX.YY                  # テレメトリ集合型は構造体のように参照できる
これは変更が小さいので別PRで

2024-02-13 07:38 UTC, kobkaz commented
スケジュール上の理由で、このバージョンはこのまま進めることにしました

2024-02-13 07:49 UTC, kobkaz commented on opslang-parser/src/lib.rs
> +            = "assert_approx_eq" __ left:expr() _ "," _ right:expr() _ "," _ tolerance:expr()
コンマなしにした

2024-02-13 07:51 UTC, merged